name: Command Line Demo

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag name of @midscene/cli'
        required: true
        default: 'latest'
      output_folder:
        description: 'Midscene report dir'
        required: true
        default: './midscene-run/report'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        env:
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npm i -g @midscene/cli@${{ github.event.inputs.tag }}
          ./command-line/sauce-demo.sh

      - name: Upload output folder
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.output_folder }}
          path: ${{ github.event.inputs.output_folder }}