name: Command Line Demo

on:
  workflow_dispatch:
    inputs:
      script_name:
        description: 'The script name to run'
        required: true
        default: './command-line/extract-github-status.sh'
      tag:
        description: 'The tag name of @midscene/cli'
        required: true
        default: 'latest'
      output_folder:
        description: 'Midscene report dir'
        required: true
        default: './command-line/midscene-run/report'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        run: |
          npm i -g @midscene/cli@${{ github.event.inputs.tag }}
          chmod +x ${{ github.event.inputs.script_name }}
          ${{ github.event.inputs.script_name }}

      - name: Upload output folder
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.output_folder }}
          path: ${{ github.event.inputs.output_folder }}