name: Puppeteer Demo

on:
  workflow_dispatch:
    inputs:
      output_folder:
        description: 'Midscene report dir'
        required: true
        default: 'puppeteer-demo/midscene_run/report'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        id: run-script
        env:
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd puppeteer-demo
          npm i pnpm -g
          pnpm install
          pnpm run test
        continue-on-error: true

      - name: Upload output folder
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: Midscene Report 
          path: ${{ github.workspace }}/${{ github.event.inputs.output_folder }}

      - name: Check if script failed
        if: steps.run-script.outcome == 'failure'
        run: exit 1
