name: Yaml Scripts Demo

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag name of @midscene/cli'
        required: true
        default: 'latest'
      output_folder:
        description: 'Midscene report directory'
        required: true
        default: 'yaml-scripts/midscene_run/report/'
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        env:
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MIDSCENE_DEBUG_AI_PROFILE: 1
        run: |
          npm i -g @midscene/cli@${{ github.event.inputs.tag }}
          cd yaml-scripts
          midscene ./midscene-scripts/

      - name: List directory contents
        run: ls -R ${{ github.workspace }}

      - name: Upload output folder
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: Midscene Report 
          path: ${{ github.workspace }}/${{ github.event.inputs.output_folder }}
